import { migrator } from './migrator';
import { migration001 } from './001_initial_schema';
import { migration002 } from './002_step1_service_engine';
import { migration003 } from './003_leave_grant_and_report_status';
import { migration004 } from './004_system_settings_fixed_and_form_snapshot';
import { migration005 } from './005_calendar_authority_engine';
import { migration006 } from './006_user_work_patterns';
import { migration007 } from './007_status_and_snapshot_v3';
import { migration008 } from './008_absence_and_engine_consolidation';
import { migration009 } from './009_care_leave_support';
import { migration010 } from './010_training_support';
import { migration011 } from './011_sick_leave_art13_support';
import { migration012 } from './012_special_leave_art14_support';
import { migration013 } from './013_care_time_art16_support';
import { migration014 } from './014_annual_leave_lot_engine';
import { migration015 } from './015_leave_calculation_snapshot_and_idempotency';
import { migration016 } from './016_approval_cycle_and_resubmit_support';
import { migration017 } from './017_position_and_flexible_approval_route_support';
import { migration018 } from './018_position_holder_type_and_constraints';
import { migration019 } from './019_workflow_policy_engine';
import { migration020 } from './020_workflow_policy_active_unique_index';
import { migration021 } from './021_attendance_book_canonical_name';
import { migration022 } from './022_cancellation_workflow_and_policy_purpose';
import { migration023 } from './023_sick_leave_canonical_overlay_and_accumulation';
import { migration024 } from './024_trip_canonical_snapshots_and_oral_order';
import { migration025 } from './025_calendar_import_and_permission';
import { migration026 } from './026_personnel_order_and_temporal_expansion';
import { migration027 } from './027_post_trip_report_policy_purpose';
import { migration028 } from './028_password_lifecycle_and_permission';
import { migration029 } from './029_official_job_titles_and_user_history';
import { migration030 } from './030_self_collision_resolution_and_authority_snapshot';
import { migration031 } from './031_workflow_policy_steps_ack_action_type';
import { migration032 } from './032_daily_work_schedule_production_contract';
import { migration033 } from './033_school_default_daily_schedule';

migrator.register(migration001);
migrator.register(migration002);
migrator.register(migration003);
migrator.register(migration004);
migrator.register(migration005);
migrator.register(migration006);
migrator.register(migration007);
migrator.register(migration008);
migrator.register(migration009);
migrator.register(migration010);
migrator.register(migration011);
migrator.register(migration012);
migrator.register(migration013);
migrator.register(migration014);
migrator.register(migration015);
migrator.register(migration016);
migrator.register(migration017);
migrator.register(migration018);
migrator.register(migration019);
migrator.register(migration020);
migrator.register(migration021);
migrator.register(migration022);
migrator.register(migration023);
migrator.register(migration024);
migrator.register(migration025);
migrator.register(migration026);
migrator.register(migration027);
migrator.register(migration028);
migrator.register(migration029);
migrator.register(migration030);
migrator.register(migration031);
migrator.register(migration032);
migrator.register(migration033);

export { migrator };

